language: cpp
jobs:
    include:
        os: linux
        dist: bionic
        language: cpp
        addons:
            apt:
              packages:
                - libgl1-mesa-dev
                - qt5-default
                - xxd
                - swig
                - libpthread-stubs0-dev
                - libqt5opengl5-dev
                - libqt5sql5-sqlite

        compiler:
            - gcc

        install:
            # first we create a directory for the CMake binaries
            - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
            - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
            # we use wget to fetch the cmake binaries
            - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.15.6/cmake-3.15.6-Linux-x86_64.tar.gz
            # extract the binaries; the output here is quite lengthy,
            # so we swallow it to not clutter up the travis console
            - tar -xvf cmake-3.15.6-Linux-x86_64.tar.gz > /dev/null
            - mv cmake-3.15.6-Linux-x86_64 cmake-install
            # add both the top-level directory and the bin directory from the archive
            # to the system PATH. By adding it to the front of the path we hide the
            # preinstalled CMake with our own.
            - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
            # don't forget to switch back to the main build directory once you are done
            - cd ${TRAVIS_BUILD_DIR}/SDK
            - git pull origin development
            - cd ${TRAVIS_BUILD_DIR}

        script: scripts/build_appimage.sh
        after_failure: cat build-appimage/CMakeFiles/CMakeError.log


