language: cpp
jobs:
    include:
        os: linux
        dist: bionic
        language: cpp
        addons:
            apt:
              packages:
                - libgl1-mesa-dev
                - qt5-default
                - xxd
                - swig
                - libpthread-stubs0-dev
                - libqt5opengl5-dev
                - libqt5sql5-sqlite
                - rpm

        compiler:
            - gcc

        install:
            # first we create a directory for the CMake binaries
            - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
            - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
            # we use wget to fetch the cmake binaries
            - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.15.6/cmake-3.15.6-Linux-x86_64.tar.gz
            # extract the binaries; the output here is quite lengthy,
            # so we swallow it to not clutter up the travis console
            - tar -xvf cmake-3.15.6-Linux-x86_64.tar.gz > /dev/null
            - mv cmake-3.15.6-Linux-x86_64 cmake-install
            # add both the top-level directory and the bin directory from the archive
            # to the system PATH. By adding it to the front of the path we hide the
            # preinstalled CMake with our own.
            - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
            # don't forget to switch back to the main build directory once you are done
            - cd ${TRAVIS_BUILD_DIR}/SDK
            - git pull origin development
            - cd ${TRAVIS_BUILD_DIR}

        script: scripts/build_appimage.sh
        after_failure: cat build-appimage/CMakeFiles/CMakeError.log

        env:
          global:
            - secure: gRfErdM33brK8kCNMdWXNqRogtUIHgzRDYAbnxxr5Ux3UjEwSFHaLJKaDGd4lJimZ1HUJEr6Z//pRAuYx497msZ/zdwgzsy1zKXSOEOywA50NMLS7da7feMujZ65Cqwxzmwq6ge6woOClLQmNZo/w6jI89DSXU/JMa5N8/VcMvA=
            - secure: gjuBvU55Hnf+J/t3f4xyFlNVq51DcTQvslKQHXwvV4GQg1pZYS2dRtGCkpASja+2MnnJ5MFBUcUctQQMVRC17VQzoccLodFnKfMcOuFLeJwayp943MinUad4KsoOzLQECW06B2hzc90hfkV29TqaQcQM+s6uEOn21gPG4zrIM/k=
          
        after_success:
            - curl --ftp-create-dirs -T *.deb -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
            - curl --ftp-create-dirs -T *.tar.gz -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
            - curl --ftp-create-dirs -T *.rpm -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
            - curl --ftp-create-dirs -T *.sh -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/
            - curl --ftp-create-dirs -T *.AppImage -u $USER@scary-squid.de:$PASSWORD ftp://scary-squid.de/


