language: cpp
jobs:
    include:
        os: linux
        dist: bionic
        language: cpp
        addons:
            apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - libgl1-mesa-dev
                - qt5-default
                - xxd
                - swig
        
        compiler:
            - clang
        script: scripts/build_appimage.sh


