language: cpp
jobs:
    include:
        os: linux
        dist: bionic
        language: cpp
        addons:
            apt:
            sources:
                - ubuntu-toolchain-r-test
            packages:
                - libgl1-mesa-dev
                - qt5-default
                - xxd
                - swig
                - libpthread-stubs0-dev
                - clang-7
                - llvm-7-dev

        compiler:
            - clang

        script: CC="/usr/bin/clang" CXX="/usr/bin/clang++" scripts/build_appimage.sh
        after_failure: cat build-appimage/CMakeFiles/CMakeError.log

